name: OpenOSV Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check 
        run: ls -R
      - name: build
        run: cargo run --release  